name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      - name: Autenticar no Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construção e envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            wallacevilela/fake-shop:latest
            wallacevilela/fake-shop:v${{ github.run_number }}


  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Construção da Imagem Docker
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Depoly dos manifestos no Kubernetes
        run: echo "Executando o comando apply"
