name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no Docker Hub
        run: echo "Executando o comando Docker login"
      - name: Construção da Imagem Docker
        run: echo "Executando o comando Docker login"
      - name: Envio da Imagem Docker
        run: echo "Executando o comando Docker push"

  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Construção da Imagem Docker
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Depoly dos manifestos no Kubernetes
        run: echo "Executando o comando apply"
